/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_u250_svg_glutils_SVGData */

#ifndef _Included_info_u250_svg_glutils_SVGData
#define _Included_info_u250_svg_glutils_SVGData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    newSvgPixmap
 * Signature: ([JIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_info_u250_svg_glutils_SVGData_newSvgPixmap
  (JNIEnv *, jclass, jlongArray, jint, jint, jint);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    startPath
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_info_u250_svg_glutils_SVGData_startPath
  (JNIEnv *, jclass);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    endPath
 * Signature: (JJDDDDD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_endPath
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    circle
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_circle
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    rect
 * Signature: (JDDDDDD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_rect
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    line
 * Signature: (JDDDD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_line
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    polygon
 * Signature: (J[DI)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_polygon
  (JNIEnv *, jclass, jlong, jdoubleArray, jint);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    moveTo
 * Signature: (JDDZ)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_moveTo
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jboolean);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    lineTo
 * Signature: (JDDZ)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_lineTo
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jboolean);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    hlineTo
 * Signature: (JDZ)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_hlineTo
  (JNIEnv *, jclass, jlong, jdouble, jboolean);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    vlineTo
 * Signature: (JDZ)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_vlineTo
  (JNIEnv *, jclass, jlong, jdouble, jboolean);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    curve3
 * Signature: (J[DZ)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_curve3
  (JNIEnv *, jclass, jlong, jdoubleArray, jboolean);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    curve4
 * Signature: (J[DZ)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_curve4
  (JNIEnv *, jclass, jlong, jdoubleArray, jboolean);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    attribute
 * Signature: (JLjava/lang/String;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_attribute
  (JNIEnv *, jclass, jlong, jstring, jstring, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    matrix
 * Signature: (JDDDDDD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_matrix
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    translate
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_translate
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    rotate
 * Signature: (J[D)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_rotate
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    scale
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_scale
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    skewX
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_skewX
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    skewY
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_skewY
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     info_u250_svg_glutils_SVGData
 * Method:    pathD
 * Signature: (JC[DI)V
 */
JNIEXPORT void JNICALL Java_info_u250_svg_glutils_SVGData_pathD
  (JNIEnv *, jclass, jlong, jchar, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
